//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchotTovarov
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckGoods
    {
        public int idCG { get; set; }
        public Nullable<int> idCheckList { get; set; }
        public Nullable<int> idGoods { get; set; }
    
        public virtual CheckList CheckList { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
