//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchotTovarov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        public int idComputer { get; set; }
        public Nullable<int> idEmployee { get; set; }
        public string Place { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
