//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchotTovarov
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliesGoods
    {
        public int idSG { get; set; }
        public Nullable<int> idSupplies { get; set; }
        public Nullable<int> idGoods { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Supplies Supplies { get; set; }
    }
}
